version: '3.4'

services:
  dndcharapi:
    image: ${DOCKER_REGISTRY-}dndcharapi
    build:
      context: .
      dockerfile: src/dndCharApi/Dockerfile
    ports:
      - "3010:3010"
    environment:
      - MongoUrl=${MongoUrl}